### PR TITLE
Feature/optimizes position numbers

### PR DESCRIPTION
**Pull request by Rockster160**
This PR adds another config option: `optimize_positions`.

This will check all of the 'sibling' positions and update them accordingly, which will fix oblong numbers, if they were created somehow.

### CODE REVIEW

**Comment by aishek** [comment]
Sorry, but I think that "somehow" is not a good reason to have such option. Could you provide scenario steps, when you need such option?

**Comment by Rockster160** [comment]
1) Moving to this gem from acts_as_list, which first of all uses 0 as the first position and also allows nil. 
2) Merging two separate sets of data, where position numbers could be far greater or different in some way. 

Is handling nil and other unexpected numbers properly a problem? As it's an option that is defaulted off, it doesn't hinder any previous code. We've been using the forked version and it works quite well.

**Comment by aishek** [comment]
I believe both of these cases should be solved not using such gem option, sorry.

**Comment by Rockster160** [comment]
No worries! 
Unfortunately, these are make-it or break-it features for us, so we'll continue to use just the forked version of the gem.

**Pull request closed without merging**
